import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FentyHeader from "./components/FentyHeader";
import RoyalBridalsFooter from "./components/RoyalBridalsFooter";

const jost = localFont({
  src: [
    {
      path: "../public/fonts/Jost-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Jost-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <FentyHeader />
        {children}
        <RoyalBridalsFooter />
      </body>
    </html>
  );
}
